# yaml-language-server: $schema=https://json.schemastore.org/pubspec.json

name: foundationdb
description: FoundationDB Bindings
version: 1.0.0

environment:
  sdk: ^3.1.3

dependencies:
  ffi: ^2.1.0
  system_info2: ^4.0.0

dev_dependencies:
  ffigen: ^9.0.1
  lints: ^2.0.0
